# Generated by Django 3.2.4 on 2021-06-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('SubTitle', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('DateTimme', models.DateTimeField(auto_now_add=True)),
                ('Slug', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(default='Anonimous', max_length=50)),
                ('Content', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blog')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comments')),
            ],
        ),
    ]
