# Generated by Django 3.2.4 on 2021-06-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='DateTimme',
            new_name='DateTime',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
