# Generated by Django 3.2.4 on 2021-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210626_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
