# Generated by Django 3.2.4 on 2021-06-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Slug',
            new_name='slug',
        ),
    ]
