# Generated by Django 3.2.4 on 2021-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comments_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewersProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='Anonymous', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Problem', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
