# Generated by Django 3.2.4 on 2021-06-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210628_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
